package com.dianping.pigeon.governor.model;

import java.util.Date;

public class Comment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.id
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.feedback_id
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    private Integer feedbackId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.userid
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.supports_number
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    private Integer supportsNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.updateTime
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.content
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.id
     *
     * @return the value of comment.id
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.id
     *
     * @param id the value for comment.id
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.feedback_id
     *
     * @return the value of comment.feedback_id
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    public Integer getFeedbackId() {
        return feedbackId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.feedback_id
     *
     * @param feedbackId the value for comment.feedback_id
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    public void setFeedbackId(Integer feedbackId) {
        this.feedbackId = feedbackId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.userid
     *
     * @return the value of comment.userid
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.userid
     *
     * @param userid the value for comment.userid
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.supports_number
     *
     * @return the value of comment.supports_number
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    public Integer getSupportsNumber() {
        return supportsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.supports_number
     *
     * @param supportsNumber the value for comment.supports_number
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    public void setSupportsNumber(Integer supportsNumber) {
        this.supportsNumber = supportsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.updateTime
     *
     * @return the value of comment.updateTime
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.updateTime
     *
     * @param updatetime the value for comment.updateTime
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.content
     *
     * @return the value of comment.content
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.content
     *
     * @param content the value for comment.content
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}