package com.dianping.pigeon.governor.model;

import java.util.Date;

public class EventReceiverModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_receiver.id
     *
     * @mbggenerated Thu Jul 21 16:46:16 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_receiver.event_signature
     *
     * @mbggenerated Thu Jul 21 16:46:16 CST 2016
     */
    private Integer eventSignature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_receiver.address
     *
     * @mbggenerated Thu Jul 21 16:46:16 CST 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_receiver.recevier_type
     *
     * @mbggenerated Thu Jul 21 16:46:16 CST 2016
     */
    private String recevierType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_receiver.updateTime
     *
     * @mbggenerated Thu Jul 21 16:46:16 CST 2016
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_receiver.id
     *
     * @return the value of event_receiver.id
     *
     * @mbggenerated Thu Jul 21 16:46:16 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_receiver.id
     *
     * @param id the value for event_receiver.id
     *
     * @mbggenerated Thu Jul 21 16:46:16 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_receiver.event_signature
     *
     * @return the value of event_receiver.event_signature
     *
     * @mbggenerated Thu Jul 21 16:46:16 CST 2016
     */
    public Integer getEventSignature() {
        return eventSignature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_receiver.event_signature
     *
     * @param eventSignature the value for event_receiver.event_signature
     *
     * @mbggenerated Thu Jul 21 16:46:16 CST 2016
     */
    public void setEventSignature(Integer eventSignature) {
        this.eventSignature = eventSignature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_receiver.address
     *
     * @return the value of event_receiver.address
     *
     * @mbggenerated Thu Jul 21 16:46:16 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_receiver.address
     *
     * @param address the value for event_receiver.address
     *
     * @mbggenerated Thu Jul 21 16:46:16 CST 2016
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_receiver.recevier_type
     *
     * @return the value of event_receiver.recevier_type
     *
     * @mbggenerated Thu Jul 21 16:46:16 CST 2016
     */
    public String getRecevierType() {
        return recevierType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_receiver.recevier_type
     *
     * @param recevierType the value for event_receiver.recevier_type
     *
     * @mbggenerated Thu Jul 21 16:46:16 CST 2016
     */
    public void setRecevierType(String recevierType) {
        this.recevierType = recevierType == null ? null : recevierType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_receiver.updateTime
     *
     * @return the value of event_receiver.updateTime
     *
     * @mbggenerated Thu Jul 21 16:46:16 CST 2016
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_receiver.updateTime
     *
     * @param updatetime the value for event_receiver.updateTime
     *
     * @mbggenerated Thu Jul 21 16:46:16 CST 2016
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}