package com.dianping.pigeon.governor.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class EventReceiverModelExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table event_receiver
     *
     * @mbggenerated Thu Jul 21 16:46:16 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table event_receiver
     *
     * @mbggenerated Thu Jul 21 16:46:16 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table event_receiver
     *
     * @mbggenerated Thu Jul 21 16:46:16 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_receiver
     *
     * @mbggenerated Thu Jul 21 16:46:16 CST 2016
     */
    public EventReceiverModelExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_receiver
     *
     * @mbggenerated Thu Jul 21 16:46:16 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_receiver
     *
     * @mbggenerated Thu Jul 21 16:46:16 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_receiver
     *
     * @mbggenerated Thu Jul 21 16:46:16 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_receiver
     *
     * @mbggenerated Thu Jul 21 16:46:16 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_receiver
     *
     * @mbggenerated Thu Jul 21 16:46:16 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_receiver
     *
     * @mbggenerated Thu Jul 21 16:46:16 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_receiver
     *
     * @mbggenerated Thu Jul 21 16:46:16 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_receiver
     *
     * @mbggenerated Thu Jul 21 16:46:16 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_receiver
     *
     * @mbggenerated Thu Jul 21 16:46:16 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_receiver
     *
     * @mbggenerated Thu Jul 21 16:46:16 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table event_receiver
     *
     * @mbggenerated Thu Jul 21 16:46:16 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andEventSignatureIsNull() {
            addCriterion("event_signature is null");
            return (Criteria) this;
        }

        public Criteria andEventSignatureIsNotNull() {
            addCriterion("event_signature is not null");
            return (Criteria) this;
        }

        public Criteria andEventSignatureEqualTo(Integer value) {
            addCriterion("event_signature =", value, "eventSignature");
            return (Criteria) this;
        }

        public Criteria andEventSignatureNotEqualTo(Integer value) {
            addCriterion("event_signature <>", value, "eventSignature");
            return (Criteria) this;
        }

        public Criteria andEventSignatureGreaterThan(Integer value) {
            addCriterion("event_signature >", value, "eventSignature");
            return (Criteria) this;
        }

        public Criteria andEventSignatureGreaterThanOrEqualTo(Integer value) {
            addCriterion("event_signature >=", value, "eventSignature");
            return (Criteria) this;
        }

        public Criteria andEventSignatureLessThan(Integer value) {
            addCriterion("event_signature <", value, "eventSignature");
            return (Criteria) this;
        }

        public Criteria andEventSignatureLessThanOrEqualTo(Integer value) {
            addCriterion("event_signature <=", value, "eventSignature");
            return (Criteria) this;
        }

        public Criteria andEventSignatureIn(List<Integer> values) {
            addCriterion("event_signature in", values, "eventSignature");
            return (Criteria) this;
        }

        public Criteria andEventSignatureNotIn(List<Integer> values) {
            addCriterion("event_signature not in", values, "eventSignature");
            return (Criteria) this;
        }

        public Criteria andEventSignatureBetween(Integer value1, Integer value2) {
            addCriterion("event_signature between", value1, value2, "eventSignature");
            return (Criteria) this;
        }

        public Criteria andEventSignatureNotBetween(Integer value1, Integer value2) {
            addCriterion("event_signature not between", value1, value2, "eventSignature");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("address not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andRecevierTypeIsNull() {
            addCriterion("recevier_type is null");
            return (Criteria) this;
        }

        public Criteria andRecevierTypeIsNotNull() {
            addCriterion("recevier_type is not null");
            return (Criteria) this;
        }

        public Criteria andRecevierTypeEqualTo(String value) {
            addCriterion("recevier_type =", value, "recevierType");
            return (Criteria) this;
        }

        public Criteria andRecevierTypeNotEqualTo(String value) {
            addCriterion("recevier_type <>", value, "recevierType");
            return (Criteria) this;
        }

        public Criteria andRecevierTypeGreaterThan(String value) {
            addCriterion("recevier_type >", value, "recevierType");
            return (Criteria) this;
        }

        public Criteria andRecevierTypeGreaterThanOrEqualTo(String value) {
            addCriterion("recevier_type >=", value, "recevierType");
            return (Criteria) this;
        }

        public Criteria andRecevierTypeLessThan(String value) {
            addCriterion("recevier_type <", value, "recevierType");
            return (Criteria) this;
        }

        public Criteria andRecevierTypeLessThanOrEqualTo(String value) {
            addCriterion("recevier_type <=", value, "recevierType");
            return (Criteria) this;
        }

        public Criteria andRecevierTypeLike(String value) {
            addCriterion("recevier_type like", value, "recevierType");
            return (Criteria) this;
        }

        public Criteria andRecevierTypeNotLike(String value) {
            addCriterion("recevier_type not like", value, "recevierType");
            return (Criteria) this;
        }

        public Criteria andRecevierTypeIn(List<String> values) {
            addCriterion("recevier_type in", values, "recevierType");
            return (Criteria) this;
        }

        public Criteria andRecevierTypeNotIn(List<String> values) {
            addCriterion("recevier_type not in", values, "recevierType");
            return (Criteria) this;
        }

        public Criteria andRecevierTypeBetween(String value1, String value2) {
            addCriterion("recevier_type between", value1, value2, "recevierType");
            return (Criteria) this;
        }

        public Criteria andRecevierTypeNotBetween(String value1, String value2) {
            addCriterion("recevier_type not between", value1, value2, "recevierType");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNull() {
            addCriterion("updateTime is null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNotNull() {
            addCriterion("updateTime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeEqualTo(Date value) {
            addCriterion("updateTime =", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotEqualTo(Date value) {
            addCriterion("updateTime <>", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThan(Date value) {
            addCriterion("updateTime >", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("updateTime >=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThan(Date value) {
            addCriterion("updateTime <", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThanOrEqualTo(Date value) {
            addCriterion("updateTime <=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIn(List<Date> values) {
            addCriterion("updateTime in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotIn(List<Date> values) {
            addCriterion("updateTime not in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeBetween(Date value1, Date value2) {
            addCriterion("updateTime between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotBetween(Date value1, Date value2) {
            addCriterion("updateTime not between", value1, value2, "updatetime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table event_receiver
     *
     * @mbggenerated do_not_delete_during_merge Thu Jul 21 16:46:16 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table event_receiver
     *
     * @mbggenerated Thu Jul 21 16:46:16 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}