package com.dianping.pigeon.governor.model;

public class EventModelWithBLOBs extends EventModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.content
     *
     * @mbggenerated Fri Jul 29 11:28:48 CST 2016
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.send_status
     *
     * @mbggenerated Fri Jul 29 11:28:48 CST 2016
     */
    private String sendStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.content
     *
     * @return the value of event.content
     *
     * @mbggenerated Fri Jul 29 11:28:48 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.content
     *
     * @param content the value for event.content
     *
     * @mbggenerated Fri Jul 29 11:28:48 CST 2016
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.send_status
     *
     * @return the value of event.send_status
     *
     * @mbggenerated Fri Jul 29 11:28:48 CST 2016
     */
    public String getSendStatus() {
        return sendStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.send_status
     *
     * @param sendStatus the value for event.send_status
     *
     * @mbggenerated Fri Jul 29 11:28:48 CST 2016
     */
    public void setSendStatus(String sendStatus) {
        this.sendStatus = sendStatus == null ? null : sendStatus.trim();
    }
}