package com.dianping.pigeon.governor.model;

import java.util.Date;

public class Feedback {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.id
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.userid
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.title
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.comments_number
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    private Integer commentsNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.supports_number
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    private Integer supportsNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.updateTime
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.content
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.id
     *
     * @return the value of feedback.id
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.id
     *
     * @param id the value for feedback.id
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.userid
     *
     * @return the value of feedback.userid
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.userid
     *
     * @param userid the value for feedback.userid
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.title
     *
     * @return the value of feedback.title
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.title
     *
     * @param title the value for feedback.title
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.comments_number
     *
     * @return the value of feedback.comments_number
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    public Integer getCommentsNumber() {
        return commentsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.comments_number
     *
     * @param commentsNumber the value for feedback.comments_number
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    public void setCommentsNumber(Integer commentsNumber) {
        this.commentsNumber = commentsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.supports_number
     *
     * @return the value of feedback.supports_number
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    public Integer getSupportsNumber() {
        return supportsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.supports_number
     *
     * @param supportsNumber the value for feedback.supports_number
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    public void setSupportsNumber(Integer supportsNumber) {
        this.supportsNumber = supportsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.updateTime
     *
     * @return the value of feedback.updateTime
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.updateTime
     *
     * @param updatetime the value for feedback.updateTime
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.content
     *
     * @return the value of feedback.content
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.content
     *
     * @param content the value for feedback.content
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}