package com.dianping.pigeon.governor.model;

import java.util.Date;

public class FeedbackSupport {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback_support.id
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback_support.feedback_id
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    private Integer feedbackId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback_support.user_name
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback_support.updateTime
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback_support.id
     *
     * @return the value of feedback_support.id
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback_support.id
     *
     * @param id the value for feedback_support.id
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback_support.feedback_id
     *
     * @return the value of feedback_support.feedback_id
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    public Integer getFeedbackId() {
        return feedbackId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback_support.feedback_id
     *
     * @param feedbackId the value for feedback_support.feedback_id
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    public void setFeedbackId(Integer feedbackId) {
        this.feedbackId = feedbackId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback_support.user_name
     *
     * @return the value of feedback_support.user_name
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback_support.user_name
     *
     * @param userName the value for feedback_support.user_name
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback_support.updateTime
     *
     * @return the value of feedback_support.updateTime
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback_support.updateTime
     *
     * @param updatetime the value for feedback_support.updateTime
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}