package com.dianping.pigeon.governor.model;

public class Host {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.ipport
     *
     * @mbggenerated
     */
    private String ipport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.appname
     *
     * @mbggenerated
     */
    private String appname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.version
     *
     * @mbggenerated
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.registry
     *
     * @mbggenerated
     */
    private Integer registry;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.id
     *
     * @return the value of host.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.id
     *
     * @param id the value for host.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.ipport
     *
     * @return the value of host.ipport
     *
     * @mbggenerated
     */
    public String getIpport() {
        return ipport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.ipport
     *
     * @param ipport the value for host.ipport
     *
     * @mbggenerated
     */
    public void setIpport(String ipport) {
        this.ipport = ipport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.appname
     *
     * @return the value of host.appname
     *
     * @mbggenerated
     */
    public String getAppname() {
        return appname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.appname
     *
     * @param appname the value for host.appname
     *
     * @mbggenerated
     */
    public void setAppname(String appname) {
        this.appname = appname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.version
     *
     * @return the value of host.version
     *
     * @mbggenerated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.version
     *
     * @param version the value for host.version
     *
     * @mbggenerated
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.registry
     *
     * @return the value of host.registry
     *
     * @mbggenerated
     */
    public Integer getRegistry() {
        return registry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.registry
     *
     * @param registry the value for host.registry
     *
     * @mbggenerated
     */
    public void setRegistry(Integer registry) {
        this.registry = registry;
    }
}