package com.dianping.pigeon.governor.model;

import java.util.Date;

public class MethodDesc {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column method_desc.method_id
     *
     * @mbggenerated Thu May 12 14:38:04 CST 2016
     */
    private Integer methodId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column method_desc.service_id
     *
     * @mbggenerated Thu May 12 14:38:04 CST 2016
     */
    private Integer serviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column method_desc.method_name
     *
     * @mbggenerated Thu May 12 14:38:04 CST 2016
     */
    private String methodName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column method_desc.method_fullname
     *
     * @mbggenerated Thu May 12 14:38:04 CST 2016
     */
    private String methodFullname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column method_desc.method_return_type
     *
     * @mbggenerated Thu May 12 14:38:04 CST 2016
     */
    private String methodReturnType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column method_desc.updateTime
     *
     * @mbggenerated Thu May 12 14:38:04 CST 2016
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column method_desc.method_id
     *
     * @return the value of method_desc.method_id
     *
     * @mbggenerated Thu May 12 14:38:04 CST 2016
     */
    public Integer getMethodId() {
        return methodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column method_desc.method_id
     *
     * @param methodId the value for method_desc.method_id
     *
     * @mbggenerated Thu May 12 14:38:04 CST 2016
     */
    public void setMethodId(Integer methodId) {
        this.methodId = methodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column method_desc.service_id
     *
     * @return the value of method_desc.service_id
     *
     * @mbggenerated Thu May 12 14:38:04 CST 2016
     */
    public Integer getServiceId() {
        return serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column method_desc.service_id
     *
     * @param serviceId the value for method_desc.service_id
     *
     * @mbggenerated Thu May 12 14:38:04 CST 2016
     */
    public void setServiceId(Integer serviceId) {
        this.serviceId = serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column method_desc.method_name
     *
     * @return the value of method_desc.method_name
     *
     * @mbggenerated Thu May 12 14:38:04 CST 2016
     */
    public String getMethodName() {
        return methodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column method_desc.method_name
     *
     * @param methodName the value for method_desc.method_name
     *
     * @mbggenerated Thu May 12 14:38:04 CST 2016
     */
    public void setMethodName(String methodName) {
        this.methodName = methodName == null ? null : methodName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column method_desc.method_fullname
     *
     * @return the value of method_desc.method_fullname
     *
     * @mbggenerated Thu May 12 14:38:04 CST 2016
     */
    public String getMethodFullname() {
        return methodFullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column method_desc.method_fullname
     *
     * @param methodFullname the value for method_desc.method_fullname
     *
     * @mbggenerated Thu May 12 14:38:04 CST 2016
     */
    public void setMethodFullname(String methodFullname) {
        this.methodFullname = methodFullname == null ? null : methodFullname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column method_desc.method_return_type
     *
     * @return the value of method_desc.method_return_type
     *
     * @mbggenerated Thu May 12 14:38:04 CST 2016
     */
    public String getMethodReturnType() {
        return methodReturnType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column method_desc.method_return_type
     *
     * @param methodReturnType the value for method_desc.method_return_type
     *
     * @mbggenerated Thu May 12 14:38:04 CST 2016
     */
    public void setMethodReturnType(String methodReturnType) {
        this.methodReturnType = methodReturnType == null ? null : methodReturnType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column method_desc.updateTime
     *
     * @return the value of method_desc.updateTime
     *
     * @mbggenerated Thu May 12 14:38:04 CST 2016
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column method_desc.updateTime
     *
     * @param updatetime the value for method_desc.updateTime
     *
     * @mbggenerated Thu May 12 14:38:04 CST 2016
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}