package com.dianping.pigeon.governor.model;

import java.util.Date;

public class OpLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oplog.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oplog.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oplog.reqIp
     *
     * @mbggenerated
     */
    private String reqip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oplog.dpaccount
     *
     * @mbggenerated
     */
    private String dpaccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oplog.opTime
     *
     * @mbggenerated
     */
    private Date optime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oplog.opType
     *
     * @mbggenerated
     */
    private Short optype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oplog.projectId
     *
     * @mbggenerated
     */
    private Integer projectid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oplog.id
     *
     * @return the value of oplog.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oplog.id
     *
     * @param id the value for oplog.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oplog.content
     *
     * @return the value of oplog.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oplog.content
     *
     * @param content the value for oplog.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oplog.reqIp
     *
     * @return the value of oplog.reqIp
     *
     * @mbggenerated
     */
    public String getReqip() {
        return reqip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oplog.reqIp
     *
     * @param reqip the value for oplog.reqIp
     *
     * @mbggenerated
     */
    public void setReqip(String reqip) {
        this.reqip = reqip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oplog.dpaccount
     *
     * @return the value of oplog.dpaccount
     *
     * @mbggenerated
     */
    public String getDpaccount() {
        return dpaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oplog.dpaccount
     *
     * @param dpaccount the value for oplog.dpaccount
     *
     * @mbggenerated
     */
    public void setDpaccount(String dpaccount) {
        this.dpaccount = dpaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oplog.opTime
     *
     * @return the value of oplog.opTime
     *
     * @mbggenerated
     */
    public Date getOptime() {
        return optime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oplog.opTime
     *
     * @param optime the value for oplog.opTime
     *
     * @mbggenerated
     */
    public void setOptime(Date optime) {
        this.optime = optime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oplog.opType
     *
     * @return the value of oplog.opType
     *
     * @mbggenerated
     */
    public Short getOptype() {
        return optype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oplog.opType
     *
     * @param optype the value for oplog.opType
     *
     * @mbggenerated
     */
    public void setOptype(Short optype) {
        this.optype = optype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oplog.projectId
     *
     * @return the value of oplog.projectId
     *
     * @mbggenerated
     */
    public Integer getProjectid() {
        return projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oplog.projectId
     *
     * @param projectid the value for oplog.projectId
     *
     * @mbggenerated
     */
    public void setProjectid(Integer projectid) {
        this.projectid = projectid;
    }
}