package com.dianping.pigeon.governor.model;

import java.util.Date;

public class ParamDesc {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column param_desc.param_id
     *
     * @mbggenerated Thu May 12 14:38:04 CST 2016
     */
    private Integer paramId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column param_desc.method_id
     *
     * @mbggenerated Thu May 12 14:38:04 CST 2016
     */
    private Integer methodId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column param_desc.param_name
     *
     * @mbggenerated Thu May 12 14:38:04 CST 2016
     */
    private String paramName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column param_desc.updateTime
     *
     * @mbggenerated Thu May 12 14:38:04 CST 2016
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column param_desc.param_desc
     *
     * @mbggenerated Thu May 12 14:38:04 CST 2016
     */
    private String paramDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column param_desc.param_id
     *
     * @return the value of param_desc.param_id
     *
     * @mbggenerated Thu May 12 14:38:04 CST 2016
     */
    public Integer getParamId() {
        return paramId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column param_desc.param_id
     *
     * @param paramId the value for param_desc.param_id
     *
     * @mbggenerated Thu May 12 14:38:04 CST 2016
     */
    public void setParamId(Integer paramId) {
        this.paramId = paramId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column param_desc.method_id
     *
     * @return the value of param_desc.method_id
     *
     * @mbggenerated Thu May 12 14:38:04 CST 2016
     */
    public Integer getMethodId() {
        return methodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column param_desc.method_id
     *
     * @param methodId the value for param_desc.method_id
     *
     * @mbggenerated Thu May 12 14:38:04 CST 2016
     */
    public void setMethodId(Integer methodId) {
        this.methodId = methodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column param_desc.param_name
     *
     * @return the value of param_desc.param_name
     *
     * @mbggenerated Thu May 12 14:38:04 CST 2016
     */
    public String getParamName() {
        return paramName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column param_desc.param_name
     *
     * @param paramName the value for param_desc.param_name
     *
     * @mbggenerated Thu May 12 14:38:04 CST 2016
     */
    public void setParamName(String paramName) {
        this.paramName = paramName == null ? null : paramName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column param_desc.updateTime
     *
     * @return the value of param_desc.updateTime
     *
     * @mbggenerated Thu May 12 14:38:04 CST 2016
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column param_desc.updateTime
     *
     * @param updatetime the value for param_desc.updateTime
     *
     * @mbggenerated Thu May 12 14:38:04 CST 2016
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column param_desc.param_desc
     *
     * @return the value of param_desc.param_desc
     *
     * @mbggenerated Thu May 12 14:38:04 CST 2016
     */
    public String getParamDesc() {
        return paramDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column param_desc.param_desc
     *
     * @param paramDesc the value for param_desc.param_desc
     *
     * @mbggenerated Thu May 12 14:38:04 CST 2016
     */
    public void setParamDesc(String paramDesc) {
        this.paramDesc = paramDesc == null ? null : paramDesc.trim();
    }
}