package com.dianping.pigeon.governor.model;

import java.util.Date;

public class Process {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process.applicant
     *
     * @mbggenerated
     */
    private String applicant;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process.event
     *
     * @mbggenerated
     */
    private Integer event;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process.args
     *
     * @mbggenerated
     */
    private String args;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process.modifyTime
     *
     * @mbggenerated
     */
    private Date modifytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process.oprator
     *
     * @mbggenerated
     */
    private String oprator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process.id
     *
     * @return the value of process.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process.id
     *
     * @param id the value for process.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process.applicant
     *
     * @return the value of process.applicant
     *
     * @mbggenerated
     */
    public String getApplicant() {
        return applicant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process.applicant
     *
     * @param applicant the value for process.applicant
     *
     * @mbggenerated
     */
    public void setApplicant(String applicant) {
        this.applicant = applicant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process.event
     *
     * @return the value of process.event
     *
     * @mbggenerated
     */
    public Integer getEvent() {
        return event;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process.event
     *
     * @param event the value for process.event
     *
     * @mbggenerated
     */
    public void setEvent(Integer event) {
        this.event = event;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process.args
     *
     * @return the value of process.args
     *
     * @mbggenerated
     */
    public String getArgs() {
        return args;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process.args
     *
     * @param args the value for process.args
     *
     * @mbggenerated
     */
    public void setArgs(String args) {
        this.args = args;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process.status
     *
     * @return the value of process.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process.status
     *
     * @param status the value for process.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process.createTime
     *
     * @return the value of process.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process.createTime
     *
     * @param createtime the value for process.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process.modifyTime
     *
     * @return the value of process.modifyTime
     *
     * @mbggenerated
     */
    public Date getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process.modifyTime
     *
     * @param modifytime the value for process.modifyTime
     *
     * @mbggenerated
     */
    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process.oprator
     *
     * @return the value of process.oprator
     *
     * @mbggenerated
     */
    public String getOprator() {
        return oprator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process.oprator
     *
     * @param oprator the value for process.oprator
     *
     * @mbggenerated
     */
    public void setOprator(String oprator) {
        this.oprator = oprator;
    }
}