package com.dianping.pigeon.governor.model;

import java.util.Date;

public class ServiceDesc {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_desc.service_id
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    private Integer serviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_desc.service_name
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    private String serviceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_desc.service_impl
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    private String serviceImpl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_desc.updateTime
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_desc.service_desc
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    private String serviceDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_desc.service_id
     *
     * @return the value of service_desc.service_id
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    public Integer getServiceId() {
        return serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_desc.service_id
     *
     * @param serviceId the value for service_desc.service_id
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    public void setServiceId(Integer serviceId) {
        this.serviceId = serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_desc.service_name
     *
     * @return the value of service_desc.service_name
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    public String getServiceName() {
        return serviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_desc.service_name
     *
     * @param serviceName the value for service_desc.service_name
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    public void setServiceName(String serviceName) {
        this.serviceName = serviceName == null ? null : serviceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_desc.service_impl
     *
     * @return the value of service_desc.service_impl
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    public String getServiceImpl() {
        return serviceImpl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_desc.service_impl
     *
     * @param serviceImpl the value for service_desc.service_impl
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    public void setServiceImpl(String serviceImpl) {
        this.serviceImpl = serviceImpl == null ? null : serviceImpl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_desc.updateTime
     *
     * @return the value of service_desc.updateTime
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_desc.updateTime
     *
     * @param updatetime the value for service_desc.updateTime
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_desc.service_desc
     *
     * @return the value of service_desc.service_desc
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    public String getServiceDesc() {
        return serviceDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_desc.service_desc
     *
     * @param serviceDesc the value for service_desc.service_desc
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    public void setServiceDesc(String serviceDesc) {
        this.serviceDesc = serviceDesc == null ? null : serviceDesc.trim();
    }
}