package com.dianping.pigeon.governor.model;

import java.util.Date;

public class ServiceNode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_node.id
     *
     * @mbggenerated Tue Jul 05 17:29:43 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_node.ip
     *
     * @mbggenerated Tue Jul 05 17:29:43 CST 2016
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_node.port
     *
     * @mbggenerated Tue Jul 05 17:29:43 CST 2016
     */
    private String port;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_node.service_name
     *
     * @mbggenerated Tue Jul 05 17:29:43 CST 2016
     */
    private String serviceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_node.group
     *
     * @mbggenerated Tue Jul 05 17:29:43 CST 2016
     */
    private String group;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_node.project_name
     *
     * @mbggenerated Tue Jul 05 17:29:43 CST 2016
     */
    private String projectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_node.updateTime
     *
     * @mbggenerated Tue Jul 05 17:29:43 CST 2016
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_node.id
     *
     * @return the value of service_node.id
     *
     * @mbggenerated Tue Jul 05 17:29:43 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_node.id
     *
     * @param id the value for service_node.id
     *
     * @mbggenerated Tue Jul 05 17:29:43 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_node.ip
     *
     * @return the value of service_node.ip
     *
     * @mbggenerated Tue Jul 05 17:29:43 CST 2016
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_node.ip
     *
     * @param ip the value for service_node.ip
     *
     * @mbggenerated Tue Jul 05 17:29:43 CST 2016
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_node.port
     *
     * @return the value of service_node.port
     *
     * @mbggenerated Tue Jul 05 17:29:43 CST 2016
     */
    public String getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_node.port
     *
     * @param port the value for service_node.port
     *
     * @mbggenerated Tue Jul 05 17:29:43 CST 2016
     */
    public void setPort(String port) {
        this.port = port == null ? null : port.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_node.service_name
     *
     * @return the value of service_node.service_name
     *
     * @mbggenerated Tue Jul 05 17:29:43 CST 2016
     */
    public String getServiceName() {
        return serviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_node.service_name
     *
     * @param serviceName the value for service_node.service_name
     *
     * @mbggenerated Tue Jul 05 17:29:43 CST 2016
     */
    public void setServiceName(String serviceName) {
        this.serviceName = serviceName == null ? null : serviceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_node.group
     *
     * @return the value of service_node.group
     *
     * @mbggenerated Tue Jul 05 17:29:43 CST 2016
     */
    public String getGroup() {
        return group;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_node.group
     *
     * @param group the value for service_node.group
     *
     * @mbggenerated Tue Jul 05 17:29:43 CST 2016
     */
    public void setGroup(String group) {
        this.group = group == null ? null : group.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_node.project_name
     *
     * @return the value of service_node.project_name
     *
     * @mbggenerated Tue Jul 05 17:29:43 CST 2016
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_node.project_name
     *
     * @param projectName the value for service_node.project_name
     *
     * @mbggenerated Tue Jul 05 17:29:43 CST 2016
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_node.updateTime
     *
     * @return the value of service_node.updateTime
     *
     * @mbggenerated Tue Jul 05 17:29:43 CST 2016
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_node.updateTime
     *
     * @param updatetime the value for service_node.updateTime
     *
     * @mbggenerated Tue Jul 05 17:29:43 CST 2016
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    @Override
    public String toString() {
        return "ServiceNode{" +
                "ip='" + ip + '\'' +
                ", port='" + port + '\'' +
                ", serviceName='" + serviceName + '\'' +
                ", group='" + group + '\'' +
                ", projectName='" + projectName + '\'' +
                '}';
    }
}