package com.dianping.pigeon.governor.dao;

import com.dianping.pigeon.governor.model.CommentSupport;
import com.dianping.pigeon.governor.model.CommentSupportExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CommentSupportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_support
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    int countByExample(CommentSupportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_support
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    int deleteByExample(CommentSupportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_support
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_support
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    int insert(CommentSupport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_support
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    int insertSelective(CommentSupport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_support
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    List<CommentSupport> selectByExample(CommentSupportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_support
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    CommentSupport selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_support
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    int updateByExampleSelective(@Param("record") CommentSupport record, @Param("example") CommentSupportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_support
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    int updateByExample(@Param("record") CommentSupport record, @Param("example") CommentSupportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_support
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    int updateByPrimaryKeySelective(CommentSupport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_support
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    int updateByPrimaryKey(CommentSupport record);
}