package com.dianping.pigeon.governor.dao;

import com.dianping.pigeon.governor.model.CommentReply;
import com.dianping.pigeon.governor.model.CommentReplyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CommentReplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_reply
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    int countByExample(CommentReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_reply
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    int deleteByExample(CommentReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_reply
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_reply
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    int insert(CommentReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_reply
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    int insertSelective(CommentReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_reply
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    List<CommentReply> selectByExample(CommentReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_reply
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    CommentReply selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_reply
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    int updateByExampleSelective(@Param("record") CommentReply record, @Param("example") CommentReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_reply
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    int updateByExample(@Param("record") CommentReply record, @Param("example") CommentReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_reply
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    int updateByPrimaryKeySelective(CommentReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_reply
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    int updateByPrimaryKey(CommentReply record);
}