package com.dianping.pigeon.governor.dao;

import com.dianping.pigeon.governor.model.EventModel;
import com.dianping.pigeon.governor.model.EventModelExample;
import com.dianping.pigeon.governor.model.EventModelWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EventModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event
     *
     * @mbggenerated Fri Jul 29 11:28:48 CST 2016
     */
    int countByExample(EventModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event
     *
     * @mbggenerated Fri Jul 29 11:28:48 CST 2016
     */
    int deleteByExample(EventModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event
     *
     * @mbggenerated Fri Jul 29 11:28:48 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event
     *
     * @mbggenerated Fri Jul 29 11:28:48 CST 2016
     */
    int insert(EventModelWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event
     *
     * @mbggenerated Fri Jul 29 11:28:48 CST 2016
     */
    int insertSelective(EventModelWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event
     *
     * @mbggenerated Fri Jul 29 11:28:48 CST 2016
     */
    List<EventModelWithBLOBs> selectByExampleWithBLOBs(EventModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event
     *
     * @mbggenerated Fri Jul 29 11:28:48 CST 2016
     */
    List<EventModel> selectByExample(EventModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event
     *
     * @mbggenerated Fri Jul 29 11:28:48 CST 2016
     */
    EventModelWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event
     *
     * @mbggenerated Fri Jul 29 11:28:48 CST 2016
     */
    int updateByExampleSelective(@Param("record") EventModelWithBLOBs record, @Param("example") EventModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event
     *
     * @mbggenerated Fri Jul 29 11:28:48 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") EventModelWithBLOBs record, @Param("example") EventModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event
     *
     * @mbggenerated Fri Jul 29 11:28:48 CST 2016
     */
    int updateByExample(@Param("record") EventModel record, @Param("example") EventModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event
     *
     * @mbggenerated Fri Jul 29 11:28:48 CST 2016
     */
    int updateByPrimaryKeySelective(EventModelWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event
     *
     * @mbggenerated Fri Jul 29 11:28:48 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(EventModelWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event
     *
     * @mbggenerated Fri Jul 29 11:28:48 CST 2016
     */
    int updateByPrimaryKey(EventModel record);
}