package com.dianping.pigeon.governor.dao;

import com.dianping.pigeon.governor.model.EventReceiverModel;
import com.dianping.pigeon.governor.model.EventReceiverModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EventReceiverModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_receiver
     *
     * @mbggenerated Fri Jul 29 11:28:48 CST 2016
     */
    int countByExample(EventReceiverModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_receiver
     *
     * @mbggenerated Fri Jul 29 11:28:48 CST 2016
     */
    int deleteByExample(EventReceiverModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_receiver
     *
     * @mbggenerated Fri Jul 29 11:28:48 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_receiver
     *
     * @mbggenerated Fri Jul 29 11:28:48 CST 2016
     */
    int insert(EventReceiverModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_receiver
     *
     * @mbggenerated Fri Jul 29 11:28:48 CST 2016
     */
    int insertSelective(EventReceiverModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_receiver
     *
     * @mbggenerated Fri Jul 29 11:28:48 CST 2016
     */
    List<EventReceiverModel> selectByExample(EventReceiverModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_receiver
     *
     * @mbggenerated Fri Jul 29 11:28:48 CST 2016
     */
    EventReceiverModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_receiver
     *
     * @mbggenerated Fri Jul 29 11:28:48 CST 2016
     */
    int updateByExampleSelective(@Param("record") EventReceiverModel record, @Param("example") EventReceiverModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_receiver
     *
     * @mbggenerated Fri Jul 29 11:28:48 CST 2016
     */
    int updateByExample(@Param("record") EventReceiverModel record, @Param("example") EventReceiverModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_receiver
     *
     * @mbggenerated Fri Jul 29 11:28:48 CST 2016
     */
    int updateByPrimaryKeySelective(EventReceiverModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_receiver
     *
     * @mbggenerated Fri Jul 29 11:28:48 CST 2016
     */
    int updateByPrimaryKey(EventReceiverModel record);
}