package com.dianping.pigeon.governor.dao;

import com.dianping.pigeon.governor.model.ExceptionDesc;
import com.dianping.pigeon.governor.model.ExceptionDescExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExceptionDescMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exception_desc
     *
     * @mbggenerated Thu May 12 14:38:04 CST 2016
     */
    int countByExample(ExceptionDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exception_desc
     *
     * @mbggenerated Thu May 12 14:38:04 CST 2016
     */
    int deleteByExample(ExceptionDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exception_desc
     *
     * @mbggenerated Thu May 12 14:38:04 CST 2016
     */
    int deleteByPrimaryKey(Integer exceptionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exception_desc
     *
     * @mbggenerated Thu May 12 14:38:04 CST 2016
     */
    int insert(ExceptionDesc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exception_desc
     *
     * @mbggenerated Thu May 12 14:38:04 CST 2016
     */
    int insertSelective(ExceptionDesc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exception_desc
     *
     * @mbggenerated Thu May 12 14:38:04 CST 2016
     */
    List<ExceptionDesc> selectByExampleWithBLOBs(ExceptionDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exception_desc
     *
     * @mbggenerated Thu May 12 14:38:04 CST 2016
     */
    List<ExceptionDesc> selectByExample(ExceptionDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exception_desc
     *
     * @mbggenerated Thu May 12 14:38:04 CST 2016
     */
    ExceptionDesc selectByPrimaryKey(Integer exceptionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exception_desc
     *
     * @mbggenerated Thu May 12 14:38:04 CST 2016
     */
    int updateByExampleSelective(@Param("record") ExceptionDesc record, @Param("example") ExceptionDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exception_desc
     *
     * @mbggenerated Thu May 12 14:38:04 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") ExceptionDesc record, @Param("example") ExceptionDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exception_desc
     *
     * @mbggenerated Thu May 12 14:38:04 CST 2016
     */
    int updateByExample(@Param("record") ExceptionDesc record, @Param("example") ExceptionDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exception_desc
     *
     * @mbggenerated Thu May 12 14:38:04 CST 2016
     */
    int updateByPrimaryKeySelective(ExceptionDesc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exception_desc
     *
     * @mbggenerated Thu May 12 14:38:04 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(ExceptionDesc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exception_desc
     *
     * @mbggenerated Thu May 12 14:38:04 CST 2016
     */
    int updateByPrimaryKey(ExceptionDesc record);
}