package com.dianping.pigeon.governor.dao;

import com.dianping.pigeon.governor.model.FeedbackSupport;
import com.dianping.pigeon.governor.model.FeedbackSupportExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FeedbackSupportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedback_support
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    int countByExample(FeedbackSupportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedback_support
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    int deleteByExample(FeedbackSupportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedback_support
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedback_support
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    int insert(FeedbackSupport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedback_support
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    int insertSelective(FeedbackSupport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedback_support
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    List<FeedbackSupport> selectByExample(FeedbackSupportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedback_support
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    FeedbackSupport selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedback_support
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    int updateByExampleSelective(@Param("record") FeedbackSupport record, @Param("example") FeedbackSupportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedback_support
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    int updateByExample(@Param("record") FeedbackSupport record, @Param("example") FeedbackSupportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedback_support
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    int updateByPrimaryKeySelective(FeedbackSupport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedback_support
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    int updateByPrimaryKey(FeedbackSupport record);
}