package com.dianping.pigeon.governor.dao;

import com.dianping.pigeon.governor.model.MethodDesc;
import com.dianping.pigeon.governor.model.MethodDescExample;
import com.dianping.pigeon.governor.model.MethodDescWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MethodDescMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table method_desc
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    int countByExample(MethodDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table method_desc
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    int deleteByExample(MethodDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table method_desc
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    int deleteByPrimaryKey(Integer methodId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table method_desc
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    int insert(MethodDescWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table method_desc
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    int insertSelective(MethodDescWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table method_desc
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    List<MethodDescWithBLOBs> selectByExampleWithBLOBs(MethodDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table method_desc
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    List<MethodDesc> selectByExample(MethodDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table method_desc
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    MethodDescWithBLOBs selectByPrimaryKey(Integer methodId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table method_desc
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    int updateByExampleSelective(@Param("record") MethodDescWithBLOBs record, @Param("example") MethodDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table method_desc
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") MethodDescWithBLOBs record, @Param("example") MethodDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table method_desc
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    int updateByExample(@Param("record") MethodDesc record, @Param("example") MethodDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table method_desc
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    int updateByPrimaryKeySelective(MethodDescWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table method_desc
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(MethodDescWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table method_desc
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    int updateByPrimaryKey(MethodDesc record);
}