package com.dianping.pigeon.governor.dao;

import com.dianping.pigeon.governor.model.OpLog;
import com.dianping.pigeon.governor.model.OpLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OpLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oplog
     *
     * @mbggenerated
     */
    int countByExample(OpLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oplog
     *
     * @mbggenerated
     */
    int deleteByExample(OpLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oplog
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oplog
     *
     * @mbggenerated
     */
    int insert(OpLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oplog
     *
     * @mbggenerated
     */
    int insertSelective(OpLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oplog
     *
     * @mbggenerated
     */
    List<OpLog> selectByExample(OpLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oplog
     *
     * @mbggenerated
     */
    OpLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oplog
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OpLog record, @Param("example") OpLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oplog
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") OpLog record, @Param("example") OpLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oplog
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OpLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oplog
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OpLog record);
}