package com.dianping.pigeon.governor.dao;

import com.dianping.pigeon.governor.model.ParamDesc;
import com.dianping.pigeon.governor.model.ParamDescExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ParamDescMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table param_desc
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    int countByExample(ParamDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table param_desc
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    int deleteByExample(ParamDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table param_desc
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    int deleteByPrimaryKey(Integer paramId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table param_desc
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    int insert(ParamDesc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table param_desc
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    int insertSelective(ParamDesc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table param_desc
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    List<ParamDesc> selectByExampleWithBLOBs(ParamDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table param_desc
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    List<ParamDesc> selectByExample(ParamDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table param_desc
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    ParamDesc selectByPrimaryKey(Integer paramId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table param_desc
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    int updateByExampleSelective(@Param("record") ParamDesc record, @Param("example") ParamDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table param_desc
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") ParamDesc record, @Param("example") ParamDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table param_desc
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    int updateByExample(@Param("record") ParamDesc record, @Param("example") ParamDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table param_desc
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    int updateByPrimaryKeySelective(ParamDesc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table param_desc
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(ParamDesc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table param_desc
     *
     * @mbggenerated Mon Jun 27 14:46:12 CST 2016
     */
    int updateByPrimaryKey(ParamDesc record);
}