package com.dianping.pigeon.governor.dao;

import com.dianping.pigeon.governor.model.ProjectOrg;
import com.dianping.pigeon.governor.model.ProjectOrgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProjectOrgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbggenerated Thu Aug 11 18:00:50 CST 2016
     */
    int countByExample(ProjectOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbggenerated Thu Aug 11 18:00:50 CST 2016
     */
    int deleteByExample(ProjectOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbggenerated Thu Aug 11 18:00:50 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbggenerated Thu Aug 11 18:00:50 CST 2016
     */
    int insert(ProjectOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbggenerated Thu Aug 11 18:00:50 CST 2016
     */
    int insertSelective(ProjectOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbggenerated Thu Aug 11 18:00:50 CST 2016
     */
    List<ProjectOrg> selectByExample(ProjectOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbggenerated Thu Aug 11 18:00:50 CST 2016
     */
    ProjectOrg selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbggenerated Thu Aug 11 18:00:50 CST 2016
     */
    int updateByExampleSelective(@Param("record") ProjectOrg record, @Param("example") ProjectOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbggenerated Thu Aug 11 18:00:50 CST 2016
     */
    int updateByExample(@Param("record") ProjectOrg record, @Param("example") ProjectOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbggenerated Thu Aug 11 18:00:50 CST 2016
     */
    int updateByPrimaryKeySelective(ProjectOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbggenerated Thu Aug 11 18:00:50 CST 2016
     */
    int updateByPrimaryKey(ProjectOrg record);
}