package com.dianping.pigeon.governor.dao;

import com.dianping.pigeon.governor.model.ProjectOwner;
import com.dianping.pigeon.governor.model.ProjectOwnerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.dao.DataAccessException;

public interface ProjectOwnerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_owner
     *
     * @mbggenerated
     */
    int countByExample(ProjectOwnerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_owner
     *
     * @mbggenerated
     */
    int deleteByExample(ProjectOwnerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_owner
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_owner
     *
     * @mbggenerated
     */
    int insert(ProjectOwner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_owner
     *
     * @mbggenerated
     */
    int insertSelective(ProjectOwner record) throws DataAccessException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_owner
     *
     * @mbggenerated
     */
    List<ProjectOwner> selectByExample(ProjectOwnerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_owner
     *
     * @mbggenerated
     */
    ProjectOwner selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_owner
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ProjectOwner record, @Param("example") ProjectOwnerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_owner
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ProjectOwner record, @Param("example") ProjectOwnerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_owner
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ProjectOwner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_owner
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ProjectOwner record);
}