package com.dianping.pigeon.governor.dao;

import com.dianping.pigeon.governor.model.ServiceDesc;
import com.dianping.pigeon.governor.model.ServiceDescExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ServiceDescMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_desc
     *
     * @mbggenerated Thu May 12 14:38:04 CST 2016
     */
    int countByExample(ServiceDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_desc
     *
     * @mbggenerated Thu May 12 14:38:04 CST 2016
     */
    int deleteByExample(ServiceDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_desc
     *
     * @mbggenerated Thu May 12 14:38:04 CST 2016
     */
    int deleteByPrimaryKey(Integer serviceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_desc
     *
     * @mbggenerated Thu May 12 14:38:04 CST 2016
     */
    int insert(ServiceDesc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_desc
     *
     * @mbggenerated Thu May 12 14:38:04 CST 2016
     */
    int insertSelective(ServiceDesc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_desc
     *
     * @mbggenerated Thu May 12 14:38:04 CST 2016
     */
    List<ServiceDesc> selectByExampleWithBLOBs(ServiceDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_desc
     *
     * @mbggenerated Thu May 12 14:38:04 CST 2016
     */
    List<ServiceDesc> selectByExample(ServiceDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_desc
     *
     * @mbggenerated Thu May 12 14:38:04 CST 2016
     */
    ServiceDesc selectByPrimaryKey(Integer serviceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_desc
     *
     * @mbggenerated Thu May 12 14:38:04 CST 2016
     */
    int updateByExampleSelective(@Param("record") ServiceDesc record, @Param("example") ServiceDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_desc
     *
     * @mbggenerated Thu May 12 14:38:04 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") ServiceDesc record, @Param("example") ServiceDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_desc
     *
     * @mbggenerated Thu May 12 14:38:04 CST 2016
     */
    int updateByExample(@Param("record") ServiceDesc record, @Param("example") ServiceDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_desc
     *
     * @mbggenerated Thu May 12 14:38:04 CST 2016
     */
    int updateByPrimaryKeySelective(ServiceDesc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_desc
     *
     * @mbggenerated Thu May 12 14:38:04 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(ServiceDesc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_desc
     *
     * @mbggenerated Thu May 12 14:38:04 CST 2016
     */
    int updateByPrimaryKey(ServiceDesc record);
}