package com.dianping.pigeon.governor.dao;

import com.dianping.pigeon.governor.model.ServiceNode;
import com.dianping.pigeon.governor.model.ServiceNodeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ServiceNodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_node
     *
     * @mbggenerated Tue Jul 05 17:29:43 CST 2016
     */
    int countByExample(ServiceNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_node
     *
     * @mbggenerated Tue Jul 05 17:29:43 CST 2016
     */
    int deleteByExample(ServiceNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_node
     *
     * @mbggenerated Tue Jul 05 17:29:43 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_node
     *
     * @mbggenerated Tue Jul 05 17:29:43 CST 2016
     */
    int insert(ServiceNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_node
     *
     * @mbggenerated Tue Jul 05 17:29:43 CST 2016
     */
    int insertSelective(ServiceNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_node
     *
     * @mbggenerated Tue Jul 05 17:29:43 CST 2016
     */
    List<ServiceNode> selectByExample(ServiceNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_node
     *
     * @mbggenerated Tue Jul 05 17:29:43 CST 2016
     */
    ServiceNode selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_node
     *
     * @mbggenerated Tue Jul 05 17:29:43 CST 2016
     */
    int updateByExampleSelective(@Param("record") ServiceNode record, @Param("example") ServiceNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_node
     *
     * @mbggenerated Tue Jul 05 17:29:43 CST 2016
     */
    int updateByExample(@Param("record") ServiceNode record, @Param("example") ServiceNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_node
     *
     * @mbggenerated Tue Jul 05 17:29:43 CST 2016
     */
    int updateByPrimaryKeySelective(ServiceNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_node
     *
     * @mbggenerated Tue Jul 05 17:29:43 CST 2016
     */
    int updateByPrimaryKey(ServiceNode record);
}