// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtobufRequest.proto

package com.dianping.pigeon.rpc.protobuf;

public final class ProtobufRequestProtos {
  private ProtobufRequestProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ProtobufRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int64 seq = 1;
    boolean hasSeq();
    long getSeq();
    
    // required int32 messageType = 2;
    boolean hasMessageType();
    int getMessageType();
    
    // required int32 callType = 3;
    boolean hasCallType();
    int getCallType();
    
    // required int32 timeout = 4;
    boolean hasTimeout();
    int getTimeout();
    
    // required string url = 5;
    boolean hasUrl();
    String getUrl();
    
    // required string methodName = 6;
    boolean hasMethodName();
    String getMethodName();
    
    // optional string version = 7;
    boolean hasVersion();
    String getVersion();
    
    // repeated string parameters = 8;
    java.util.List<String> getParametersList();
    int getParametersCount();
    String getParameters(int index);
    
    // repeated .MapEntity contexts = 9;
    java.util.List<com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.MapEntity> 
        getContextsList();
    com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.MapEntity getContexts(int index);
    int getContextsCount();
    java.util.List<? extends com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.MapEntityOrBuilder> 
        getContextsOrBuilderList();
    com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.MapEntityOrBuilder getContextsOrBuilder(
        int index);
  }
  public static final class ProtobufRequest extends
      com.google.protobuf.GeneratedMessage
      implements ProtobufRequestOrBuilder {
    // Use ProtobufRequest.newBuilder() to construct.
    private ProtobufRequest(Builder builder) {
      super(builder);
    }
    private ProtobufRequest(boolean noInit) {}
    
    private static final ProtobufRequest defaultInstance;
    public static ProtobufRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public ProtobufRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.internal_static_ProtobufRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.internal_static_ProtobufRequest_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int64 seq = 1;
    public static final int SEQ_FIELD_NUMBER = 1;
    private long seq_;
    public boolean hasSeq() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getSeq() {
      return seq_;
    }
    
    // required int32 messageType = 2;
    public static final int MESSAGETYPE_FIELD_NUMBER = 2;
    private int messageType_;
    public boolean hasMessageType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getMessageType() {
      return messageType_;
    }
    
    // required int32 callType = 3;
    public static final int CALLTYPE_FIELD_NUMBER = 3;
    private int callType_;
    public boolean hasCallType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getCallType() {
      return callType_;
    }
    
    // required int32 timeout = 4;
    public static final int TIMEOUT_FIELD_NUMBER = 4;
    private int timeout_;
    public boolean hasTimeout() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getTimeout() {
      return timeout_;
    }
    
    // required string url = 5;
    public static final int URL_FIELD_NUMBER = 5;
    private java.lang.Object url_;
    public boolean hasUrl() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getUrl() {
      java.lang.Object ref = url_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          url_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUrlBytes() {
      java.lang.Object ref = url_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string methodName = 6;
    public static final int METHODNAME_FIELD_NUMBER = 6;
    private java.lang.Object methodName_;
    public boolean hasMethodName() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public String getMethodName() {
      java.lang.Object ref = methodName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          methodName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getMethodNameBytes() {
      java.lang.Object ref = methodName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        methodName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string version = 7;
    public static final int VERSION_FIELD_NUMBER = 7;
    private java.lang.Object version_;
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public String getVersion() {
      java.lang.Object ref = version_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          version_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated string parameters = 8;
    public static final int PARAMETERS_FIELD_NUMBER = 8;
    private com.google.protobuf.LazyStringList parameters_;
    public java.util.List<String>
        getParametersList() {
      return parameters_;
    }
    public int getParametersCount() {
      return parameters_.size();
    }
    public String getParameters(int index) {
      return parameters_.get(index);
    }
    
    // repeated .MapEntity contexts = 9;
    public static final int CONTEXTS_FIELD_NUMBER = 9;
    private java.util.List<com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.MapEntity> contexts_;
    public java.util.List<com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.MapEntity> getContextsList() {
      return contexts_;
    }
    public java.util.List<? extends com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.MapEntityOrBuilder> 
        getContextsOrBuilderList() {
      return contexts_;
    }
    public int getContextsCount() {
      return contexts_.size();
    }
    public com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.MapEntity getContexts(int index) {
      return contexts_.get(index);
    }
    public com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.MapEntityOrBuilder getContextsOrBuilder(
        int index) {
      return contexts_.get(index);
    }
    
    private void initFields() {
      seq_ = 0L;
      messageType_ = 0;
      callType_ = 0;
      timeout_ = 0;
      url_ = "";
      methodName_ = "";
      version_ = "";
      parameters_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      contexts_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasSeq()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMessageType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCallType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimeout()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUrl()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMethodName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, seq_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, messageType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, callType_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, timeout_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getUrlBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getMethodNameBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getVersionBytes());
      }
      for (int i = 0; i < parameters_.size(); i++) {
        output.writeBytes(8, parameters_.getByteString(i));
      }
      for (int i = 0; i < contexts_.size(); i++) {
        output.writeMessage(9, contexts_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, seq_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, messageType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, callType_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, timeout_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getUrlBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getMethodNameBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getVersionBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < parameters_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(parameters_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getParametersList().size();
      }
      for (int i = 0; i < contexts_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, contexts_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.ProtobufRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.ProtobufRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.ProtobufRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.ProtobufRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.ProtobufRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.ProtobufRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.ProtobufRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.ProtobufRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.ProtobufRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.ProtobufRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.ProtobufRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.ProtobufRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.internal_static_ProtobufRequest_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.internal_static_ProtobufRequest_fieldAccessorTable;
      }
      
      // Construct using com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.ProtobufRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getContextsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        seq_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        messageType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        callType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        timeout_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        url_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        methodName_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        version_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        parameters_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        if (contextsBuilder_ == null) {
          contexts_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000100);
        } else {
          contextsBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.ProtobufRequest.getDescriptor();
      }
      
      public com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.ProtobufRequest getDefaultInstanceForType() {
        return com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.ProtobufRequest.getDefaultInstance();
      }
      
      public com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.ProtobufRequest build() {
        com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.ProtobufRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.ProtobufRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.ProtobufRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.ProtobufRequest buildPartial() {
        com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.ProtobufRequest result = new com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.ProtobufRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.seq_ = seq_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.messageType_ = messageType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.callType_ = callType_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.timeout_ = timeout_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.url_ = url_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.methodName_ = methodName_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.version_ = version_;
        if (((bitField0_ & 0x00000080) == 0x00000080)) {
          parameters_ = new com.google.protobuf.UnmodifiableLazyStringList(
              parameters_);
          bitField0_ = (bitField0_ & ~0x00000080);
        }
        result.parameters_ = parameters_;
        if (contextsBuilder_ == null) {
          if (((bitField0_ & 0x00000100) == 0x00000100)) {
            contexts_ = java.util.Collections.unmodifiableList(contexts_);
            bitField0_ = (bitField0_ & ~0x00000100);
          }
          result.contexts_ = contexts_;
        } else {
          result.contexts_ = contextsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.ProtobufRequest) {
          return mergeFrom((com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.ProtobufRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.ProtobufRequest other) {
        if (other == com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.ProtobufRequest.getDefaultInstance()) return this;
        if (other.hasSeq()) {
          setSeq(other.getSeq());
        }
        if (other.hasMessageType()) {
          setMessageType(other.getMessageType());
        }
        if (other.hasCallType()) {
          setCallType(other.getCallType());
        }
        if (other.hasTimeout()) {
          setTimeout(other.getTimeout());
        }
        if (other.hasUrl()) {
          setUrl(other.getUrl());
        }
        if (other.hasMethodName()) {
          setMethodName(other.getMethodName());
        }
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (!other.parameters_.isEmpty()) {
          if (parameters_.isEmpty()) {
            parameters_ = other.parameters_;
            bitField0_ = (bitField0_ & ~0x00000080);
          } else {
            ensureParametersIsMutable();
            parameters_.addAll(other.parameters_);
          }
          onChanged();
        }
        if (contextsBuilder_ == null) {
          if (!other.contexts_.isEmpty()) {
            if (contexts_.isEmpty()) {
              contexts_ = other.contexts_;
              bitField0_ = (bitField0_ & ~0x00000100);
            } else {
              ensureContextsIsMutable();
              contexts_.addAll(other.contexts_);
            }
            onChanged();
          }
        } else {
          if (!other.contexts_.isEmpty()) {
            if (contextsBuilder_.isEmpty()) {
              contextsBuilder_.dispose();
              contextsBuilder_ = null;
              contexts_ = other.contexts_;
              bitField0_ = (bitField0_ & ~0x00000100);
              contextsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getContextsFieldBuilder() : null;
            } else {
              contextsBuilder_.addAllMessages(other.contexts_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasSeq()) {
          
          return false;
        }
        if (!hasMessageType()) {
          
          return false;
        }
        if (!hasCallType()) {
          
          return false;
        }
        if (!hasTimeout()) {
          
          return false;
        }
        if (!hasUrl()) {
          
          return false;
        }
        if (!hasMethodName()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              seq_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              messageType_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              callType_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              timeout_ = input.readInt32();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              url_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              methodName_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              version_ = input.readBytes();
              break;
            }
            case 66: {
              ensureParametersIsMutable();
              parameters_.add(input.readBytes());
              break;
            }
            case 74: {
              com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.MapEntity.Builder subBuilder = com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.MapEntity.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addContexts(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int64 seq = 1;
      private long seq_ ;
      public boolean hasSeq() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getSeq() {
        return seq_;
      }
      public Builder setSeq(long value) {
        bitField0_ |= 0x00000001;
        seq_ = value;
        onChanged();
        return this;
      }
      public Builder clearSeq() {
        bitField0_ = (bitField0_ & ~0x00000001);
        seq_ = 0L;
        onChanged();
        return this;
      }
      
      // required int32 messageType = 2;
      private int messageType_ ;
      public boolean hasMessageType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getMessageType() {
        return messageType_;
      }
      public Builder setMessageType(int value) {
        bitField0_ |= 0x00000002;
        messageType_ = value;
        onChanged();
        return this;
      }
      public Builder clearMessageType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        messageType_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 callType = 3;
      private int callType_ ;
      public boolean hasCallType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getCallType() {
        return callType_;
      }
      public Builder setCallType(int value) {
        bitField0_ |= 0x00000004;
        callType_ = value;
        onChanged();
        return this;
      }
      public Builder clearCallType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        callType_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 timeout = 4;
      private int timeout_ ;
      public boolean hasTimeout() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getTimeout() {
        return timeout_;
      }
      public Builder setTimeout(int value) {
        bitField0_ |= 0x00000008;
        timeout_ = value;
        onChanged();
        return this;
      }
      public Builder clearTimeout() {
        bitField0_ = (bitField0_ & ~0x00000008);
        timeout_ = 0;
        onChanged();
        return this;
      }
      
      // required string url = 5;
      private java.lang.Object url_ = "";
      public boolean hasUrl() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getUrl() {
        java.lang.Object ref = url_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          url_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUrl(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        url_ = value;
        onChanged();
        return this;
      }
      public Builder clearUrl() {
        bitField0_ = (bitField0_ & ~0x00000010);
        url_ = getDefaultInstance().getUrl();
        onChanged();
        return this;
      }
      void setUrl(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        url_ = value;
        onChanged();
      }
      
      // required string methodName = 6;
      private java.lang.Object methodName_ = "";
      public boolean hasMethodName() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getMethodName() {
        java.lang.Object ref = methodName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          methodName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setMethodName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        methodName_ = value;
        onChanged();
        return this;
      }
      public Builder clearMethodName() {
        bitField0_ = (bitField0_ & ~0x00000020);
        methodName_ = getDefaultInstance().getMethodName();
        onChanged();
        return this;
      }
      void setMethodName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        methodName_ = value;
        onChanged();
      }
      
      // optional string version = 7;
      private java.lang.Object version_ = "";
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public String getVersion() {
        java.lang.Object ref = version_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          version_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setVersion(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        version_ = value;
        onChanged();
        return this;
      }
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000040);
        version_ = getDefaultInstance().getVersion();
        onChanged();
        return this;
      }
      void setVersion(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000040;
        version_ = value;
        onChanged();
      }
      
      // repeated string parameters = 8;
      private com.google.protobuf.LazyStringList parameters_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureParametersIsMutable() {
        if (!((bitField0_ & 0x00000080) == 0x00000080)) {
          parameters_ = new com.google.protobuf.LazyStringArrayList(parameters_);
          bitField0_ |= 0x00000080;
         }
      }
      public java.util.List<String>
          getParametersList() {
        return java.util.Collections.unmodifiableList(parameters_);
      }
      public int getParametersCount() {
        return parameters_.size();
      }
      public String getParameters(int index) {
        return parameters_.get(index);
      }
      public Builder setParameters(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParametersIsMutable();
        parameters_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addParameters(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParametersIsMutable();
        parameters_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllParameters(
          java.lang.Iterable<String> values) {
        ensureParametersIsMutable();
        super.addAll(values, parameters_);
        onChanged();
        return this;
      }
      public Builder clearParameters() {
        parameters_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
        return this;
      }
      void addParameters(com.google.protobuf.ByteString value) {
        ensureParametersIsMutable();
        parameters_.add(value);
        onChanged();
      }
      
      // repeated .MapEntity contexts = 9;
      private java.util.List<com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.MapEntity> contexts_ =
        java.util.Collections.emptyList();
      private void ensureContextsIsMutable() {
        if (!((bitField0_ & 0x00000100) == 0x00000100)) {
          contexts_ = new java.util.ArrayList<com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.MapEntity>(contexts_);
          bitField0_ |= 0x00000100;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.MapEntity, com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.MapEntity.Builder, com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.MapEntityOrBuilder> contextsBuilder_;
      
      public java.util.List<com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.MapEntity> getContextsList() {
        if (contextsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(contexts_);
        } else {
          return contextsBuilder_.getMessageList();
        }
      }
      public int getContextsCount() {
        if (contextsBuilder_ == null) {
          return contexts_.size();
        } else {
          return contextsBuilder_.getCount();
        }
      }
      public com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.MapEntity getContexts(int index) {
        if (contextsBuilder_ == null) {
          return contexts_.get(index);
        } else {
          return contextsBuilder_.getMessage(index);
        }
      }
      public Builder setContexts(
          int index, com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.MapEntity value) {
        if (contextsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContextsIsMutable();
          contexts_.set(index, value);
          onChanged();
        } else {
          contextsBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setContexts(
          int index, com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.MapEntity.Builder builderForValue) {
        if (contextsBuilder_ == null) {
          ensureContextsIsMutable();
          contexts_.set(index, builderForValue.build());
          onChanged();
        } else {
          contextsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addContexts(com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.MapEntity value) {
        if (contextsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContextsIsMutable();
          contexts_.add(value);
          onChanged();
        } else {
          contextsBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addContexts(
          int index, com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.MapEntity value) {
        if (contextsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContextsIsMutable();
          contexts_.add(index, value);
          onChanged();
        } else {
          contextsBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addContexts(
          com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.MapEntity.Builder builderForValue) {
        if (contextsBuilder_ == null) {
          ensureContextsIsMutable();
          contexts_.add(builderForValue.build());
          onChanged();
        } else {
          contextsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addContexts(
          int index, com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.MapEntity.Builder builderForValue) {
        if (contextsBuilder_ == null) {
          ensureContextsIsMutable();
          contexts_.add(index, builderForValue.build());
          onChanged();
        } else {
          contextsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllContexts(
          java.lang.Iterable<? extends com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.MapEntity> values) {
        if (contextsBuilder_ == null) {
          ensureContextsIsMutable();
          super.addAll(values, contexts_);
          onChanged();
        } else {
          contextsBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearContexts() {
        if (contextsBuilder_ == null) {
          contexts_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000100);
          onChanged();
        } else {
          contextsBuilder_.clear();
        }
        return this;
      }
      public Builder removeContexts(int index) {
        if (contextsBuilder_ == null) {
          ensureContextsIsMutable();
          contexts_.remove(index);
          onChanged();
        } else {
          contextsBuilder_.remove(index);
        }
        return this;
      }
      public com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.MapEntity.Builder getContextsBuilder(
          int index) {
        return getContextsFieldBuilder().getBuilder(index);
      }
      public com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.MapEntityOrBuilder getContextsOrBuilder(
          int index) {
        if (contextsBuilder_ == null) {
          return contexts_.get(index);  } else {
          return contextsBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.MapEntityOrBuilder> 
           getContextsOrBuilderList() {
        if (contextsBuilder_ != null) {
          return contextsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(contexts_);
        }
      }
      public com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.MapEntity.Builder addContextsBuilder() {
        return getContextsFieldBuilder().addBuilder(
            com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.MapEntity.getDefaultInstance());
      }
      public com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.MapEntity.Builder addContextsBuilder(
          int index) {
        return getContextsFieldBuilder().addBuilder(
            index, com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.MapEntity.getDefaultInstance());
      }
      public java.util.List<com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.MapEntity.Builder> 
           getContextsBuilderList() {
        return getContextsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.MapEntity, com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.MapEntity.Builder, com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.MapEntityOrBuilder> 
          getContextsFieldBuilder() {
        if (contextsBuilder_ == null) {
          contextsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.MapEntity, com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.MapEntity.Builder, com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.MapEntityOrBuilder>(
                  contexts_,
                  ((bitField0_ & 0x00000100) == 0x00000100),
                  getParentForChildren(),
                  isClean());
          contexts_ = null;
        }
        return contextsBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:ProtobufRequest)
    }
    
    static {
      defaultInstance = new ProtobufRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ProtobufRequest)
  }
  
  public interface MapEntityOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string key = 1;
    boolean hasKey();
    String getKey();
    
    // optional string value = 2;
    boolean hasValue();
    String getValue();
  }
  public static final class MapEntity extends
      com.google.protobuf.GeneratedMessage
      implements MapEntityOrBuilder {
    // Use MapEntity.newBuilder() to construct.
    private MapEntity(Builder builder) {
      super(builder);
    }
    private MapEntity(boolean noInit) {}
    
    private static final MapEntity defaultInstance;
    public static MapEntity getDefaultInstance() {
      return defaultInstance;
    }
    
    public MapEntity getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.internal_static_MapEntity_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.internal_static_MapEntity_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string key = 1;
    public static final int KEY_FIELD_NUMBER = 1;
    private java.lang.Object key_;
    public boolean hasKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          key_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string value = 2;
    public static final int VALUE_FIELD_NUMBER = 2;
    private java.lang.Object value_;
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          value_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      key_ = "";
      value_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getValueBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getValueBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.MapEntity parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.MapEntity parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.MapEntity parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.MapEntity parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.MapEntity parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.MapEntity parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.MapEntity parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.MapEntity parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.MapEntity parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.MapEntity parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.MapEntity prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.MapEntityOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.internal_static_MapEntity_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.internal_static_MapEntity_fieldAccessorTable;
      }
      
      // Construct using com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.MapEntity.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        key_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.MapEntity.getDescriptor();
      }
      
      public com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.MapEntity getDefaultInstanceForType() {
        return com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.MapEntity.getDefaultInstance();
      }
      
      public com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.MapEntity build() {
        com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.MapEntity result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.MapEntity buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.MapEntity result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.MapEntity buildPartial() {
        com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.MapEntity result = new com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.MapEntity(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.key_ = key_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.MapEntity) {
          return mergeFrom((com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.MapEntity)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.MapEntity other) {
        if (other == com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.MapEntity.getDefaultInstance()) return this;
        if (other.hasKey()) {
          setKey(other.getKey());
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              key_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              value_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string key = 1;
      private java.lang.Object key_ = "";
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setKey(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      void setKey(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
      }
      
      // optional string value = 2;
      private java.lang.Object value_ = "";
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setValue(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      void setValue(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:MapEntity)
    }
    
    static {
      defaultInstance = new MapEntity(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:MapEntity)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtobufRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProtobufRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_MapEntity_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MapEntity_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025ProtobufRequest.proto\"\272\001\n\017ProtobufRequ" +
      "est\022\013\n\003seq\030\001 \002(\003\022\023\n\013messageType\030\002 \002(\005\022\020\n" +
      "\010callType\030\003 \002(\005\022\017\n\007timeout\030\004 \002(\005\022\013\n\003url\030" +
      "\005 \002(\t\022\022\n\nmethodName\030\006 \002(\t\022\017\n\007version\030\007 \001" +
      "(\t\022\022\n\nparameters\030\010 \003(\t\022\034\n\010contexts\030\t \003(\013" +
      "2\n.MapEntity\"\'\n\tMapEntity\022\013\n\003key\030\001 \001(\t\022\r" +
      "\n\005value\030\002 \001(\tB9\n com.dianping.pigeon.rpc" +
      ".protobufB\025ProtobufRequestProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ProtobufRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ProtobufRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ProtobufRequest_descriptor,
              new java.lang.String[] { "Seq", "MessageType", "CallType", "Timeout", "Url", "MethodName", "Version", "Parameters", "Contexts", },
              com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.ProtobufRequest.class,
              com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.ProtobufRequest.Builder.class);
          internal_static_MapEntity_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_MapEntity_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_MapEntity_descriptor,
              new java.lang.String[] { "Key", "Value", },
              com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.MapEntity.class,
              com.dianping.pigeon.rpc.protobuf.ProtobufRequestProtos.MapEntity.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
